server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luquinhas29/luquinhas29-config-server
          search-paths: 'greeting-server*'
          #username: luquinhas29
          #password: K@uamiguel2201
          #default-label: main
