server:
  port: 8084

spring:
  application:
    name: greeting-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luquinhas29/luquinhas29-config-server
          username: luquinhas29
          password: K@uamiguel2201
        default-label: main
